### ISSUE TITLE
Implement/make use of Ashley ECS

### ISSUE THREAD

**Issue by jonaengs** [jonaengs/minigolf-with-friends#6]
Create systems:
- [x] Objectives

Create components:
- [x] Player
- [x] Objective

Create Factory:
- [x] Factory

**Comment by AleksanderWK** [comment]
Hva gjør Player systemet? Står ikke i dokumentet.

**Comment by jonaengs** [comment]
Godt spm. Kanskje @runarsae husker?

**Comment by runarsae** [comment]
Ser ikke ut som om vi har planlagt å ha et Player-system. De vi har i følge dokumentet er Physics, Graphics, Power-ups og Objective.

**Comment by jonaengs** [comment]
Sant. Fjernet det.
